### ISSUE TITLE
Add Pseudo Code for Other Classes

### ISSUE THREAD

**Issue by Julian88Tex** [patrick-yan-sf/FindDuplicates#1]
@patrick-yan-sf would you mind adding the additional Classes with a little bit of pseudocode (perhaps on a separate branch) so it's clear what you imagine the end result is? I may know an engineer who would like to continue working on this. Thanks!

**Comment by patrick-yan-sf** [comment]
@Julian88Tex sure - I was planning on flushing it out a bit more shortly.  At least get it to the point where you can schedule something to be run and it would create the duplicate sets.

**Comment by Julian88Tex** [comment]
@patrick-yan-sf cool, that would be awesome :-). Also, I did a little searching on github for other repos that use this method.... didn't find any that seem to be doing what we are trying to, but here's a link just in case: https://github.com/search?l=Apex&q=%22Datacloud.FindDuplicates%22&type=Code

**Comment by patrick-yan-sf** [comment]
@Julian88Tex - I've got it working - at a very basic level.  And hopefully the example in there is simple enough that others can continue working on it.  I've put some thoughts into the readme file.

**Comment by Julian88Tex** [comment]
@patrick-yan-sf Thanks for doing that. As soon as I get a chance I'll plan on QAing it so that I'm sure I understand and will add any additional notes.

**Comment by Julian88Tex** [comment]
@patrick-yan-sf finished QAing and added a demo video and how to steps to my PR
